language: node_js
node_js:
  - '11'
stages:
- lint
- test
- build
- release
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run coveralls
    - stage: build
      script:
        - npm run build
    - stage: release
      if: branch = master
      script:
        - npm run build
      deploy:
        provider: script
        cleanup: true
        script:
          - npx semantic-release
